require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PhasesController do

  def mock_phase(stubs={})
    @mock_phase ||= mock_model(Phase, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all phases as @phases" do
      Phase.stub(:all) { [mock_phase] }
      get :index
      assigns(:phases).should eq([mock_phase])
    end
  end

  describe "GET show" do
    it "assigns the requested phase as @phase" do
      Phase.stub(:find).with("37") { mock_phase }
      get :show, :id => "37"
      assigns(:phase).should be(mock_phase)
    end
  end

  describe "GET new" do
    it "assigns a new phase as @phase" do
      Phase.stub(:new) { mock_phase }
      get :new
      assigns(:phase).should be(mock_phase)
    end
  end

  describe "GET edit" do
    it "assigns the requested phase as @phase" do
      Phase.stub(:find).with("37") { mock_phase }
      get :edit, :id => "37"
      assigns(:phase).should be(mock_phase)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created phase as @phase" do
        Phase.stub(:new).with({'these' => 'params'}) { mock_phase(:save => true) }
        post :create, :phase => {'these' => 'params'}
        assigns(:phase).should be(mock_phase)
      end

      it "redirects to the created phase" do
        Phase.stub(:new) { mock_phase(:save => true) }
        post :create, :phase => {}
        response.should redirect_to(phase_url(mock_phase))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved phase as @phase" do
        Phase.stub(:new).with({'these' => 'params'}) { mock_phase(:save => false) }
        post :create, :phase => {'these' => 'params'}
        assigns(:phase).should be(mock_phase)
      end

      it "re-renders the 'new' template" do
        Phase.stub(:new) { mock_phase(:save => false) }
        post :create, :phase => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested phase" do
        Phase.stub(:find).with("37") { mock_phase }
        mock_phase.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :phase => {'these' => 'params'}
      end

      it "assigns the requested phase as @phase" do
        Phase.stub(:find) { mock_phase(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:phase).should be(mock_phase)
      end

      it "redirects to the phase" do
        Phase.stub(:find) { mock_phase(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(phase_url(mock_phase))
      end
    end

    describe "with invalid params" do
      it "assigns the phase as @phase" do
        Phase.stub(:find) { mock_phase(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:phase).should be(mock_phase)
      end

      it "re-renders the 'edit' template" do
        Phase.stub(:find) { mock_phase(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested phase" do
      Phase.stub(:find).with("37") { mock_phase }
      mock_phase.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the phases list" do
      Phase.stub(:find) { mock_phase }
      delete :destroy, :id => "1"
      response.should redirect_to(phases_url)
    end
  end

end
